version: "1.1"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: javeriana

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on: 
      - mysql 
      
  webstudio:
    image: openltablets/webstudio
    restart: always
    ports:
      - 9080:8080
    depends_on: 
      - mysql 

  ws:
    image: openltablets/ws
    restart: always
    ports:
      - 9081:8080
    depends_on: 
      - mysql
      - webstudio