version: "3.7"

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: javeriana
      MYSQL_HOST: '0.0.0.0'
      MYSQL_ROOT_HOST: '%'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on: 
      - mysql 
      
  webstudio:
    image: openltablets/webstudio
    restart: always
    ports:
      - 9080:8080
    depends_on: 
      - mysql 

  ws:
    image: openltablets/ws
    restart: always
    ports:
      - 9081:8080
    depends_on: 
      - mysql
      - webstudio